### ISSUE TITLE
Dodanie BBO Handviewera

### ISSUE THREAD

**Issue by Jaom** [emkael/jfrpary-bidding-data#1]
Natchnęło mnie to (klikamy GIB):
http://adamkubica.cz/prez1617/Hluk/table.php?group=1&round=5&table=1&seg=1

Średnie to jest, bo nie ma licytacji... Aczkolwiek my licytację mamy. Handviewera można by roboczo podlinkować gdzieś obok numeru rozdania, a LIN utworzyć tak by:
a) zawierał nazwiska licytujących (może inicjał imienia i kilka pierwszych  liter nazwiska?)
b) zawierał to samo rozdanie ale w licytowane przez różne pary (nie wiem czy tak się da) - klikanie NEXT przenosiłoby na kolejny stół na którym grano rozdanie. Można by też linkować do każdego wpisu, ale chyba sensu to nie ma - aktualnie wydaje się, że taki podgląd licytacji jest bardziej wygodny (acz nie daje GIBa)

**Comment by emkael** [comment]
> zawierał nazwiska licytujących (może inicjał imienia i kilka pierwszych liter nazwiska?)

Dawno jest w TODO. Główny mankament: losowa kolejność zawodników w parach sprawia, że "ficzer" robi się bardziej bezużyteczny niż użyteczny.

> zawierał to samo rozdanie ale w licytowane przez różne pary (nie wiem czy tak się da) - klikanie NEXT przenosiłoby na kolejny stół na którym grano rozdanie

Pojedynczy handviewer obsługuje więcej niż jeden stół? Nie mówiąc o tym, że sam "standard" LIN - więcej niż 2?

Klepanie LINów na stronie kojarzy mi się nierozłącznie z kwiatkami typu: http://www.pzbs.pl/wyniki/kadra/2017/jun/kryterium-1/t/trunda1.html

Z kolei przełączanie między różnymi handviewerami brzmi jak coś strasznie ciężkiego (i nie wiem, czy mającego uzasadnienie w przypadku braku zapisu przebiegu rozgrywki).

Sumarycznie - gdy jest wyświetlana tylko licytacja, wartość dodawana przez HV do funkcjonalności "wyświetlanie licytacji" jest niedodatnia.
Wartość dodawana do przez HV do funkcjonalności "wpięcie HV w Pary" jest nieujemna, ale wykracza poza zakres tego ćwiczenia.

**Comment by Jaom** [comment]
LIN obsługuje wiele rozdań.
LIN obsługuje co najmniej dwa stoły (teamy). 
Tyle z grubsza wiem. Oczekiwałbym jednak najgorszego w temacie jak bardzo można tego nadużyć.

Handviewer mógłby być wygodny, gdyby obsługiwał kolejne stoły NEXTem. Dodatkowo daje bonus, że widać, który wist jest ok na dany kontrakt. 

Fakt, że nazwiska byłyby kłopotliwe w kontekście nieprzypisania przeciwników.

Hover / clikc na nr pary mógłby pokazywać nazwiska, co mogłoby stanowić lepsze rozwiązanie.

BTW - marzy mi się taki widok rozdania:
w tabelce z lewami na miana klikamy daną liczbę lew (czyli miano kontraktu granego z konkretnej ręki) na co przy kartach wistującego pojawiają się liczby lew, które weźmie po którym wiście - i można sobie pogrywać te karty

**Comment by emkael** [comment]
> LIN obsługuje wiele rozdań.

Sformatowane tak, że da się przekazać do HV (w parametrze URLa)?

> Handviewer mógłby być wygodny, gdyby obsługiwał kolejne stoły NEXTem.

A potrafi?

> Dodatkowo daje bonus, że widać, który wist jest ok na dany kontrakt.

Ponawiam pytanie - jaki jest związek jakiegokolwiek wyświetlania rozkładu i analizy w widne handviewerem z wyświetlaniem licytacji?

Do wpięcia handviewera nie potrzeba w ogóle tabelki z licytacją (jak widać na czeskim przykładzie), podejrzenie, który wist jest skuteczny, jest jednakowo przydatne, gdy mamy licytację, jak i bez niej.  
A wpinanie handviewera tylko dlatego, że akurat wyświetla tę tabelkę, którą chcemy wyświetlić, ma daleko niekorzystny stosunek kosztu do korzyści.

Na drodze Twoim marzeniom chwilowo stoi fakt, że projekt nazywa się `jfrpary-bidding-data`, a nie `jfrpary-handviewer` i w związku z tym mogę zaoferować na przykład dwa siwerty empatii.

**Comment by Jaom** [comment]
> Sformatowane tak, że da się przekazać do HV (w parametrze URLa)?

Parametr URLa to treść LINa. HandViewer obsługuje mecze (dwustołowe raptem i wielorozdaniowe)
No idea czy to znaczy, że da się w niego wrzucić "traveller".

>A potrafi?

No idea. 

> Ponawiam pytanie - jaki jest związek jakiegokolwiek wyświetlania rozkładu i analizy w widne handviewerem z wyświetlaniem licytacji?

Niewielki, przyznaję. Sam końcowy kontrakt to daje (i to robią w czechach), aczkolwiek bez licytacji to głupio wygląda i nieprzyjemnie się ogląda.

> Do wpięcia handviewera nie potrzeba w ogóle tabelki z licytacją (jak widać na czeskim przykładzie), podejrzenie, który wist jest skuteczny, jest jednakowo przydatne, gdy mamy licytację, jak i bez niej.
> A wpinanie handviewera tylko dlatego, że akurat wyświetla tę tabelkę, którą chcemy wyświetlić, ma daleko niekorzystny stosunek kosztu do korzyści.

Owszem, ale jeśli jest np. ochota pokazania i licytacji, i nazwisk (to nieaktualne, bo turnieje par tego w zasadzie nie wspierają w zakresie E<->W i N<->S), i wistu  to brzmiało jakby było niegłupie. Zwracam uwagę na czas przeszły.
