### ISSUE TITLE
Bundle w repo

### ISSUE THREAD

**Issue by starsep** [emkael/jfrpary-bidding-data#2]
Czemu bundle są w repo? Na githubie do tego służą [releases](https://github.com/emkael/jfrpary-bidding-data/releases).

**Comment by emkael** [comment]
Bo:
 - program jest wersjonowany w bardzo luźny sposób (dużo niestabilnych zmian)
 - utrzymywane są dwie równoległe wersje binariów, niekoniecznie wydawane w tym samym momencie

Czy pytanie brzmi "czemu są w repozytorium", czy "czemu ich nie ma w tagach"?

**Comment by starsep** [comment]
Pytanie brzmi "czemu są w repozytorium?". Repozytorium po sklonowaniu waży około 150MB. Nie jest to wielki problem, ale jakiś tam jest.

**Comment by emkael** [comment]
Ok, mogę obiecać, że następne wersje binarek już tu nie wylądują, ale repozytorium się nie skurczy, bo filter-branch+push -f nie wchodzi w grę (bo Twoja obecność tu pokazuje, że jednak ktoś jeszcze z tego repozytorium korzystać).

**Comment by starsep** [comment]
Dzięki!
Rozumiem decyzję, popieram niechęć do `push -f`, szczególnie w publicznym repozytorium.
